Repository akashic-games/headless-driver, pull requests merged in 2019-04, with the labels that each got.

#13 Refactor AMFlowClient
  packages/headless-driver/src/__tests__/index.ts
  packages/headless-driver/src/play/amflow/AMFlowClient.ts
  packages/headless-driver/src/play/amflow/AMFlowStore.ts
  packages/headless-driver/src/play/amflow/ErrorFactory.ts
Labels: bug

#12 Enabled to update CHANGELOG.md
  .gitignore
  .remarkignore
  CHANGELOG.md
  build/publishAndUpdateChangelog.js
  package-lock.json
  package.json
Labels: enhancement

#16 Add CHANGELOG.md
  CHANGELOG.md
Labels: other

#19 Fix to execute script when trailing line comment
  package-lock.json
  packages/headless-driver-runner-v1/src/platform/assets/NodeScriptAsset.ts
  packages/headless-driver-runner-v2/src/platform/assets/NodeScriptAsset.ts
  packages/headless-driver/src/__tests__/contents/content-v1/script/main.js
  packages/headless-driver/src/__tests__/contents/content-v2/script/main.js
Labels: bug
