Repository akashic-games/headless-driver, pull requests merged in 2019-06, with the labels that each got.

#38 【v0.4.3】内部コンポーネントの更新(engineFiles@2.1.17, engineFiles@1.1.9)
  packages/headless-driver-runner-v2/package.json
Labels: enhancement

#39 【v0.4.3】内部コンポーネントの更新(engineFiles@2.1.18, engineFiles@1.1.9)
  packages/headless-driver-runner-v2/package.json
Labels: enhancement

#40 Export ContentParameters and GameJsonParameters
  packages/headless-driver-runner-v1/package-lock.json
  packages/headless-driver-runner-v2/package-lock.json
  packages/headless-driver/src/play/Content.ts
Labels: bug

#43 Add `dependencies` label to lerna-changelog
  package.json
Labels: other

#44 【v0.4.4】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)
  packages/headless-driver-runner-v2/package-lock.json
  packages/headless-driver-runner-v2/package.json
Labels: enhancement

#46 【v0.4.5】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)
  packages/headless-driver-runner-v1/package-lock.json
  packages/headless-driver-runner-v2/package-lock.json
Labels: enhancement

#47 【v0.4.6】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)
  packages/headless-driver-runner-v1/package-lock.json
  packages/headless-driver-runner-v2/package-lock.json
Labels: enhancement

#48 【v0.4.7】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)
  packages/headless-driver-runner-v1/package-lock.json
  packages/headless-driver-runner-v2/package-lock.json
Labels: enhancement

#49 【v0.4.8】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)
  packages/headless-driver-runner-v1/package-lock.json
  packages/headless-driver-runner-v2/package-lock.json
Labels: enhancement

#50 【v0.4.9】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)
  packages/headless-driver-runner-v1/package-lock.json
  packages/headless-driver-runner-v2/package-lock.json
Labels: enhancement

#51 【v0.4.10】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)
  packages/headless-driver-runner-v1/package-lock.json
  packages/headless-driver-runner-v2/package-lock.json
Labels: enhancement

#45 何も変更を加えずにpublishするnpm-scriptを追加
  build/prepareRepublish.js
  build/publishAndUpdateChangelog.js
  package-lock.json
  package.json
Labels: other
