Repository akashic-games/headless-driver, pull requests merged in 2020-06, with the labels that each got.

#147 .npmrcの削除と直下の.npmrcをgit管理外にする対応
  .npmrc
Labels: bug

#149 publishスクリプトにタグ指定オプションを追加
  build/publishAndUpdateChangelog.js
  package.json
Labels: other

#157 【v1.1.19】内部コンポーネントの更新(engineFiles@3.0.0-beta.6, engineFiles@2.1.41, engineFiles@1.1.15)
  .npmrc
  packages/headless-driver-runner-v1/.npmrc
  packages/headless-driver-runner-v1/package.json
  packages/headless-driver-runner-v2/.npmrc
  packages/headless-driver-runner-v2/package.json
  packages/headless-driver-runner-v3/.npmrc
  packages/headless-driver-runner-v3/package.json
  packages/headless-driver-runner-v3/src/platform/NullAudioPlayer.ts
  packages/headless-driver-runner-v3/src/platform/NullGlyph.ts
  packages/headless-driver-runner-v3/src/platform/NullGlyphFactory.ts
  packages/headless-driver-runner-v3/src/platform/NullRenderer.ts
  packages/headless-driver-runner-v3/src/platform/NullSurface.ts
  packages/headless-driver-runner-v3/src/platform/NullSurfaceAtlas.ts
  packages/headless-driver-runner-v3/src/platform/NullVideoPlayer.ts
  packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
  packages/headless-driver-runner-v3/src/platform/ResourceFactory.ts
  packages/headless-driver-runner-v3/src/platform/assets/Asset.ts
  packages/headless-driver-runner-v3/src/platform/assets/NodeScriptAsset.ts
  packages/headless-driver-runner-v3/src/platform/assets/NodeTextAsset.ts
  packages/headless-driver-runner-v3/src/platform/assets/NullAudioAsset.ts
  packages/headless-driver-runner-v3/src/platform/assets/NullImageAsset.ts
  packages/headless-driver-runner-v3/src/platform/assets/NullVideoAsset.ts
  packages/headless-driver-runner/.npmrc
  packages/headless-driver-runner/package.json
  packages/headless-driver/.npmrc
  packages/headless-driver/package.json
  packages/headless-driver/src/__tests__/AMFlowSpec.ts
  packages/headless-driver/src/play/amflow/AMFlowClient.ts
  packages/headless-driver/src/play/amflow/AMFlowStore.ts
Labels: enhancement
