Repository akashic-games/headless-driver, pull requests merged in 2021-05, with the labels that each got.

#249 trusted フラグの追加
  packages/headless-driver-runner-v1/src/RunnerV1.ts
  packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
  packages/headless-driver-runner-v1/src/platform/ResourceFactory.ts
  packages/headless-driver-runner-v1/src/platform/assets/NodeScriptAsset.ts
  packages/headless-driver-runner-v1/src/platform/assets/NodeTextAsset.ts
  packages/headless-driver-runner-v2/src/RunnerV2.ts
  packages/headless-driver-runner-v2/src/platform/PlatformV2.ts
  packages/headless-driver-runner-v2/src/platform/ResourceFactory.ts
  packages/headless-driver-runner-v2/src/platform/assets/NodeScriptAsset.ts
  packages/headless-driver-runner-v2/src/platform/assets/NodeTextAsset.ts
  packages/headless-driver-runner-v3/src/RunnerV3.ts
  packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
  packages/headless-driver-runner-v3/src/platform/ResourceFactory.ts
  packages/headless-driver-runner-v3/src/platform/assets/NodeScriptAsset.ts
  packages/headless-driver-runner-v3/src/platform/assets/NodeTextAsset.ts
  packages/headless-driver-runner/src/Platform.ts
  packages/headless-driver-runner/src/Runner.ts
  packages/headless-driver-runner/src/index.ts
  packages/headless-driver-runner/src/types/trustedFunctions.d.ts
  packages/headless-driver-runner/src/utilsInSandbox.ts
  packages/headless-driver/src/__tests__/helpers/MockRunnerManager.ts
  packages/headless-driver/src/__tests__/runSpec.ts
  packages/headless-driver/src/runner/RunnerManager.ts
  packages/headless-driver/src/utils.ts
Labels: enhancement

#250 node-canvas へプライマリサーフェスの描画内容を出力する機能の追加
  packages/headless-driver-runner-v1/src/RunnerV1.ts
  packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
  packages/headless-driver-runner-v2/src/RunnerV2.ts
  packages/headless-driver-runner-v2/src/platform/PlatformV2.ts
  packages/headless-driver-runner-v3/src/RunnerV3.ts
  packages/headless-driver-runner-v3/src/platform/NodeCanvasResourceFactory.ts
  packages/headless-driver-runner-v3/src/platform/NullResourceFactory.ts
  packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
  packages/headless-driver-runner/src/Platform.ts
  packages/headless-driver-runner/src/Runner.ts
  packages/headless-driver-runner/src/index.ts
  packages/headless-driver-runner/src/types.ts
  packages/headless-driver/package.json
  packages/headless-driver/src/__tests__/fixtures/content-v1/script/main.js
  packages/headless-driver/src/__tests__/fixtures/content-v2/script/main.js
  packages/headless-driver/src/__tests__/fixtures/content-v3/.gitignore
  packages/headless-driver/src/__tests__/fixtures/content-v3/actual/.gitkeep
  packages/headless-driver/src/__tests__/fixtures/content-v3/diff/.gitkeep
  packages/headless-driver/src/__tests__/fixtures/content-v3/expected/frame_000.png
  packages/headless-driver/src/__tests__/fixtures/content-v3/expected/frame_001.png
  packages/headless-driver/src/__tests__/fixtures/content-v3/expected/frame_002.png
  packages/headless-driver/src/__tests__/fixtures/content-v3/expected/frame_003.png
  packages/headless-driver/src/__tests__/fixtures/content-v3/expected/frame_004.png
  packages/headless-driver/src/__tests__/fixtures/content-v3/script/main.js
  packages/headless-driver/src/__tests__/rendererSpec.ts
  packages/headless-driver/src/__tests__/runSpec.ts
  packages/headless-driver/src/runner/RunnerManager.ts
Labels: enhancement

#252 `g` の名前空間を export するように
  packages/headless-driver-runner-v1/src/RunnerV1.ts
  packages/headless-driver-runner-v2/src/RunnerV2.ts
  packages/headless-driver-runner-v3/src/RunnerV3.ts
  packages/headless-driver-runner/src/Runner.ts
  packages/headless-driver/src/__tests__/runSpec.ts
Labels: enhancement

#254 `Runner#platform`, `DumpedPlaylog` を公開プロパティに変更
  packages/headless-driver-runner-v1/src/RunnerV1.ts
  packages/headless-driver-runner-v2/src/RunnerV2.ts
  packages/headless-driver-runner-v3/src/RunnerV3.ts
  packages/headless-driver-runner/src/Runner.ts
  packages/headless-driver/src/index.ts
  packages/headless-driver/src/play/PlayManager.ts
  packages/headless-driver/src/play/amflow/AMFlowClient.ts
  packages/headless-driver/src/play/amflow/AMFlowStore.ts
  packages/headless-driver/src/play/amflow/types.ts
Labels: other

#255 `Runner#advanceUntil()` の挙動を修正
  packages/headless-driver-runner-v1/src/RunnerV1.ts
  packages/headless-driver-runner-v2/src/RunnerV2.ts
  packages/headless-driver-runner-v3/src/RunnerV3.ts
  packages/headless-driver-runner/src/Runner.ts
Labels: bug

#256 #248 にて`trustedFunctions` が存在しない場合に常に `require("@akashic/engine-files")` へとフォールバックされていた挙動を修正
  .github/workflows/test.yml
  packages/headless-driver-runner-v3/src/engineFiles.ts
  packages/headless-driver-runner-v3/src/requireEngineFiles.ts
  packages/headless-driver/src/__tests__/.gitignore
  packages/headless-driver/src/__tests__/RunnerSpec.ts
  packages/headless-driver/src/__tests__/fixtures/engineFilesV3/engineFilesV3_0_15.debug.js
  packages/headless-driver/src/__tests__/fixtures/engineFilesV3/engineFilesV3_0_15.release.js
  packages/headless-driver/src/__tests__/runSpec.ts
  packages/headless-driver/src/__tests__/tmp/.gitkeep
  packages/headless-driver/src/runner/RunnerManager.ts
Labels: bug

#259 【v1.7.3】内部コンポーネントの更新(engineFiles@3.0.15, engineFiles@2.1.54, engineFiles@1.1.16)
  packages/headless-driver-runner-v2/package.json
  packages/headless-driver-runner-v3/package.json
Labels: enhancement

#258 テストのリネームなど
  packages/headless-driver-runner/package.json
  packages/headless-driver-runner/src/__tests__/Looper.spec.ts
  packages/headless-driver-runner/tsconfig.json
  packages/headless-driver/package.json
  packages/headless-driver/src/__tests__/PlaySpec.ts
  packages/headless-driver/src/__tests__/play.spec.ts
  packages/headless-driver/src/__tests__/renderer.spec.ts
  packages/headless-driver/src/__tests__/run.spec.ts
  packages/headless-driver/src/__tests__/runner.spec.ts
  packages/headless-driver/src/play/__tests__/AMFlowClientManager.spec.ts
  packages/headless-driver/src/play/__tests__/PlayManager.spec.ts
  packages/headless-driver/src/runner/RunnerManager.ts
  packages/headless-driver/tsconfig.eslint.json
  packages/headless-driver/tsconfig.json
Labels: other
